### Authors
GET http://localhost:8080/authors
Authorization: Basic admin@test.com 123
Accept: application/json

###
POST http://localhost:8080/authors
Authorization: Basic admin@test.com 123
Content-Type: application/json

{
  "name" : "Humayun Ahammed"
}

### Book Categoreis
GET http://localhost:8080/book-categories
Authorization: Basic admin@test.com 123

###
POST http://localhost:8080/book-categories
Authorization: Basic admin@test.com 123
Content-Type: application/json

{
  "name" : "Short Story"
}

### Books
GET http://localhost:8080/books
Authorization: Basic admin@test.com 123
Accept: application/json

### Books projected
GET http://localhost:8080/books?projection=bookProjector
Authorization: Basic admin@test.com 123
Accept: application/json

### deactivate
PUT http://localhost:8080/custom/books/deactivate/3
Authorization: Basic admin@test.com 123

###
POST http://localhost:8080/custom/books
Authorization: Basic admin@test.com 123
Content-Type: application/json

{
  "isbn": 100002,
  "title": "Ever Green",
  "categoryId": 2,
  "authorIds": [1,2]
}

###
POST http://localhost:8080/books
Authorization: Basic admin@test.com 123
Content-Type: application/json

{
  "id": 4,
  "isbn": 100004,
  "title": "Ever Green Part II",
  "category": "/book-categories/1",
  "active": true,
  "authors": ["/authors/1","/authors/2"]
}

### forming nested resource save request
PUT http://localhost:8080/books/4
Authorization: Basic admin@test.com 123
Content-Type: application/json

{
"id": 4,
"isbn": 1000005,
"title": "Ever Green Part II",
"category": "/book-categories/1",
"active": false,
"authors": ["/authors/1","/authors/2"]
}
###
GET http://localhost:8080/books/1
Authorization: Basic admin@test.com 123
